# Generated by Django 5.0.1 on 2024-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='ciudad',
        ),
    ]
